### ISSUE TITLE
samostatná knihovna bez sandboxu

### ISSUE THREAD

**Issue by janmarek** [Vrtak-CZ/nette-doctrine-sandbox#2]
Ahoj Patriku, četl jsem o tomhle na fóru a vypadá to jako něco, po čem jsem vždy toužil. Bohužel je to ale zamontované do nějakého sandboxu. Myslíš, že bys to moh vypreparovat do samostatného repozitáře? Zvládnul bych to i sám, ale pokud to má nějaké testy, tak ty by se k tomu hodily.

**Comment by Vrtak-CZ** [comment]
Je to v plánu... Jen si pořád nejsem jistej tím namespacem...

váhám jestli
- `Nella\Addons`
- `Nella\NetteAddons`
- `Nella\Extras`
- `Nella\NetteExtras`
- `Nella\Nette`

Mám totiž takových balíků pro Nette víc...

**Comment by janmarek** [comment]
Jestli jde o tenhle vážnej problém, tak bych dal Nella\NetteAddons.

**Comment by kukulich** [comment]
Asi je to nejošklivější, ale souhlasím s Honzou, že `Nella\NetteAddons`. Obsahuje to tvůj jmenný prostor i informaci o tom, že to je rozšíření pro Nette.

**Comment by dmvk** [comment]
A co Nella\Extensions (Nella\NetteExtensions)? Přece jen to dědí od CompilerExtension ..

**Comment by janmarek** [comment]
Addons je obecnější. Všechny rozšíření nette frameworku nemusí být extension kontejneru.

**Comment by dmvk** [comment]
Právě proto bych rozlišoval Addons (komponenty ...) a Extensions

**Comment by Vrtak-CZ** [comment]
@davidmoravek přesně jak říká @janmarek né všechny balíky které mám připravené jsou Extensions (proto v seznamu tahle varianta chybí). Mít dva namespace Addons a Extensions jsem taky zvažoval, ale to by v tom byl ještě větší bordel.

**Comment by Vrtak-CZ** [comment]
viz: https://github.com/nella/nette-addon-doctrine
